import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ReactNode } from "react";
import styles from "./layout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJs App Router Example",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className={styles.navContainer}>
          <ul className={styles.navList}>
            <li>
              <Link href="/" legacyBehavior>
                <a className={styles.navLink}>Home</a>
              </Link>
            </li>
            <li>
              <Link href="/about" legacyBehavior>
                <a className={styles.navLink}>About</a>
              </Link>
            </li>
            <li>
              <Link href="/Services" legacyBehavior>
                <a className={styles.navLink}>Services</a>
              </Link>
            </li>
            <li>
              <Link href="/not-found" legacyBehavior>
                <a className={styles.navLink}>ContactUs</a>
              </Link>
            </li>
          </ul>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
